### PR TITLE
An example of minimally testing TeX Live binaries

### PR DESCRIPTION
**Pull request by yihui**
This is an example for https://github.com/TeX-Live/installer/pull/13#issuecomment-628900933

### CODE REVIEW

**Comment by norbusan** [comment]
See https://ci.appveyor.com/project/norbusan/installer/builds/32888078 it fails unfortunately.

**Comment by yihui** [comment]
That's intentional. I just want to show that you could have used this simple test to discover early (in the future) that TeX Live is broken before users discover it.

**Comment by norbusan** [comment]
I am not convinced. The updmap error looks bogus, I haven't heard that in real life till now.
One would need to investigate **what** are the errors that happened and why something didn't work.

On Unix this is quite easy, while on Windows there are zillions of reasons a trivial command might fail, most of them out of our hands.

**Comment by yihui** [comment]
I don't know if there are zillions of reasons for `pdflatex` to fail on Windows. Let's talk about this issue first: https://tug.org/pipermail/tex-live/2020-May/045655.html I wonder if it is out of your hands.

I think the test I added in this PR could have helped you discover this problem earlier. TeX Live shouldn't have been broken so badly that it cannot even compile a minimal document. Even if the problem is out of your hands, it is good for you to know _as soon as possible_ (which is the point of "continuous integration" services like AppVeyor) that TeX Live is totally failing, because you will have to deal with it no matter what the reason is (unless you wish to ignore Windows users).

I'm not sure what the "updmap error" you mentioned was, but running `pdflatex test.tex` gave this error:

```
This is pdfTeX, Version 3.14159265-2.6-1.40.21 (TeX Live 2020/W32TeX) (preloaded format=pdflatex)
 restricted \write18 enabled.
Running the command C:\texlive\bin\win32\fmtutil-user.exe
I can't find the format file `pdflatex.fmt'!
kpathsea: Running mktexfmt pdflatex.fmt
The command name is C:\texlive\bin\win32\mktexfmt
Command exited with code 1
```

**Pull request closed without merging**
