### PR TITLE
Migrate to GitHub Actions

### PR DESCRIPTION
**Pull request by wtsnjp**
As you may know, [Travis CI has announced](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing) that they will shut down travis-ci.org in near future. Probably due to that, the build status for this repository on Travis CI is "failing" from a while ago.

[GitHub Actions](https://github.com/features/actions) is a newer service by GitHub that provides a CI environment. Now it seems to be popular among projects hosted on GitHub. I made a simple setup for GitHub Actions. This should perform the equivalent checking that has been done by Travis CI and AppVeyor.

### CODE REVIEW

**Comment by wtsnjp** [comment]
You can check the build status on GitHub Actions in my fork here: <https://github.com/wtsnjp/installer/actions/runs/798981827>

**Comment by norbusan** [comment]
Thanks, that is great. I have also started to migrate the actual compile test from travis to github actions, but this is work in progress, see the actually committed file in Build/source/.github

**Comment by wtsnjp** [comment]
You might want to delete the former CIs in "Settings > Webhooks" just for your reference.

**Comment by norbusan** [comment]
Indeed, thanks for reminding me!

**Pull request merged**
