### PR TITLE
Update zh_CN.po

### PR DESCRIPTION
**Pull request by NightSharp**

### CODE REVIEW

**Comment by norbusan** [comment]
Hi
thanks, but that doesn't work out of various reasons:

* this is only a mirror of the main svn, so please send changes to the TL mailing list
* you delete quite a lot of entries from the translation file, I don't think this is a good idea

Best

**Comment by NightSharp** [comment]
> Hi thanks, but that doesn't work out of various reasons:
> 
>     * this is only a mirror of the main svn, so please send changes to the TL mailing list
> 
>     * you delete quite a lot of entries from the translation file, I don't think this is a good idea
> 
> 
> Best

@norbusan 

OK, I see. But there are something I'm not so clear:
- Would you mind telling me how to submit translations to the main svn correctly? I'm not able to find the access...
- I downloaded the `messages.pot` and did the translation based on it with Poedit. Why it differs a lot from the previous `zh_CN.po` ? Maybe these items are used for older version but not in use for 2021 ?
- When encountering this kind of case, is it suitable to remove those outdated items from the po file? or otherwise I should update the translation on the old one instead of the latest pot file?

**Comment by kberry** [comment]
- Would you mind telling me how to submit translations to the main svn correctly? I'm not able to find the access...

Please email the diff to ***@***.***

Then the other Chinese translators have a chance to review it.

    Why it differs a lot from the previous `zh_CN.po` ?

As far as I know, the currently-checked-in messages.pot is up to date.
So I don't know what's going on. --thanks, karl.

**Comment by norbusan** [comment]
Hi @NightSharp 

again, thanks for your work on that.

> * Would you mind telling me how to submit translations to the main svn correctly? I'm not able to find the access...

As Karl wrote, please send it to the mailing list of TeX Live: See here https://www.tug.org/texlive/lists.html for details (it seems email adr cannot be mentioned here)

> * I downloaded the `messages.pot` and did the translation based on it with Poedit. Why it differs a lot from the previous `zh_CN.po` ? Maybe these items are used for older version but not in use for 2021 ?

Interesting. Maybe the `zh_CN.po` hasn't been updated in a long long time.

> * When encountering this kind of case, is it suitable to remove those outdated items from the po file? or otherwise I should update the translation on the old one instead of the latest pot file?

The `messages.pot` is, as Karl wrote, up to date and correct. So messages that are not in there don't need to be kept. 

Best

Norbert

**Pull request closed without merging**
