### PR TITLE
Try to install luatex

### PR DESCRIPTION
**Pull request by yihui**
This PR is not meant to be merged. I'm trying to figure out why TeX Live started to fail to compile documents to PDF: https://ci.appveyor.com/project/yihui/tinytex/builds/32863862 I want to see if it fails in this repo, too.

### CODE REVIEW

**Comment by yihui** [comment]
The failure could be reproduce here, too: https://ci.appveyor.com/project/norbusan/installer/builds/32864245

```
tlmgr install luatex
tlmgr.pl: package repository http://ctan.math.washington.edu/tex-archive/systems/texlive/tlnet (verified)
[1/9, ??:??/??:??] install: cm [233k]
[2/9, 00:01/00:10] install: etex [12k]
[3/9, 00:01/00:10] install: hyph-utf8 [16k]
[4/9, 00:01/00:09] install: knuth-lib [30k]
TLUtils::check_file: checksums differ for C:\Users\appveyor\AppData\Local\Temp\1\9T4zszQ5xG\9J9DaNnHbA/luatex.win32.tar.xz:
TLUtils::check_file:   tlchecksum=2e22def143606949b8eab4ce7a0850768e1d78ed9bccdfc35db54f6caabb22788f324c323c4b9f51827463f3c5e848c62821beef24d00ead81078d7c03f49232, arg=c0ce160951a2c73f733c573db352d13ccb953c9d2313f09b2535118c02a906b473877c981b7afd44cb15461a567bb788e10522d8bfbb13288f11ee7e1cf0f23c
TLUtils::check_file:   removing C:\Users\appveyor\AppData\Local\Temp\1\9T4zszQ5xG\9J9DaNnHbA/luatex.win32.tar.xz, but saving copy in C:\Users\appveyor\AppData\Local\Temp\1\eEHrlA5eyj
TLPDB::_install_package: downloading did not succeed (check_file_and_remove failed)
[5/9, 00:01/00:08] install: luatex.win32 [1780k]
[6/9, 00:01/00:01] install: luatex [13k]
[7/9, 00:01/00:01] install: plain [70k]
[8/9, 00:01/00:01] install: tex-ini-files [4k]
[9/9, 00:02/00:02] install: unicode-data [285k]
Cannot run wrapper due to missing luatex.dll
running mktexlsr ...
done running mktexlsr.
Cannot run wrapper due to missing luatex.dll
Cannot run wrapper due to missing luatex.dll
```

Any ideas on what's going on here? @kberry @norbusan Sorry for disturbing you, but it has affected multiple (TinyTeX) users, e.g.,

- https://github.com/yihui/tinytex/issues/210 
- https://stackoverflow.com/q/61777248/559676
- https://yihui.org/tinytex/r/#comment-4911017275
- https://yihui.org/tinytex/r/#comment-4911814769
- https://yihui.org/tinytex/r/#comment-4913186294

**Comment by yihui** [comment]
Oh... I just noticed that someone mentioned in yihui/tinytex#210 that this issue had been reported. Sorry for the noise (was busy debugging the problem). I'll read the bug report in the mailing list. Thanks!

**Comment by norbusan** [comment]
I answer there, yes, there are checksum problems, we are investigating.

**Comment by yihui** [comment]
Thanks! It might be a good idea to put some simple tests in this repo, to make sure the basic installation actually works (in addition to testing that the installer works).

**Comment by norbusan** [comment]
We already do a full test installation before pushing out new packages (on the tug.org server), as well as running some tlmgr commands in the installation.

We do **not** check that actual documents can be formatted. This is on my TODO list for quite some time now (something like CI testing for TeX packages, sty etc), but haven't come around yet.

**Comment by yihui** [comment]
Great to know! Thanks again!

**Comment by kberry** [comment]
We could test document typesetting along with the other things we
already test, but it would not have caught this particular error, which
was Windows only. We're not going to be running any Windows binaries on
tug.org. So if you want that to be tested, it'll have to be done
somewhere else, by someone other than me :). (In fact, I can't think of
any of our myriad update failures that would have been caught by such a
test, which has made me less than enthused to spend time on it.)

If you're living on the bleeding edge and taking every daily update
(understandable), it seems like it would not be bad for you to have your
own sanity test before pushing it out to tinytex users. Just a thought :).
--best, karl.

**Comment by yihui** [comment]
@kberry Actually this case could have been easily caught by CI testing, since @norbusan has enabled the AppVeyor service (which runs on Windows). You can see a minimal example at https://github.com/TeX-Live/installer/pull/14, and it failed with the error below (https://ci.appveyor.com/project/norbusan/installer/builds/32888078):

```
pdflatex test.tex
This is pdfTeX, Version 3.14159265-2.6-1.40.21 (TeX Live 2020/W32TeX) (preloaded format=pdflatex)
 restricted \write18 enabled.
Running the command C:\texlive\bin\win32\fmtutil-user.exe
I can't find the format file `pdflatex.fmt'!
kpathsea: Running mktexfmt pdflatex.fmt
The command name is C:\texlive\bin\win32\mktexfmt
Command exited with code 1
```

It only required three lines of code to start the minimal testing: https://github.com/TeX-Live/installer/pull/14/files

I'll be happy to contribute more tests if you like. Thanks!

**Comment by yihui** [comment]
> it seems like it would not be bad for you to have your own sanity test before pushing it out to tinytex users. Just a thought :)

BTW, thanks for the advice! To be clear, TinyTeX is essentially a way to install TeX Live, and users usually use the installation scripts to install the daily builds, instead of installing a prebuilt distribution. I don't really have control over what I push out to TinyTeX users, and I'm pretty much at your mercy.

**Pull request closed without merging**
