### PR TITLE
Use Travis CI to test installing on Linux and macOS

### PR DESCRIPTION
**Pull request by nwhetsell**
This pull request adds minimal installations of TeX Live on Linux and macOS using [Travis CI](https://travis-ci.org/nwhetsell/installer/builds/383213433).

### CODE REVIEW

**Comment by nwhetsell** [comment]
> We don't need TravisCI builds, since we do on every automated rebuild a full installation on Unix already. Only Windows testing is necessary.

The installer was also recently broken on macOS (https://tex.stackexchange.com/questions/432617/texlive-2018-installation-error-missing-lz4#comment-1085293 – I wrote that comment). Using Travis CI to test on Linux may be unnecessary, but I think testing on macOS is a good idea.

> The question is how can we incorporate tests of AppVeyor into this? First of all all of our building is based on a local subversion server and checkout, not on git and not on a github-like service (none of them allow for our big repos).
> 
> If you have any idea, let me know ;-)

This is a bit beyond my knowledge, I’m afraid, but might it be possible to do something like what (I imagine) is happening at https://github.com/TeX-Live/luatex? Only, instead of bringing in the whole SVN repository every 30 minutes, just commit and push the installation scripts (if necessary)?

**Comment by norbusan** [comment]
Umpf, including wget in the images is not realistic since it is not available AFAIR generally for it.

**Comment by nwhetsell** [comment]
I’m not sure I understand, but at any rate the installations on Travis CI are currently succeeding: https://travis-ci.org/nwhetsell/installer/builds/383213433.

**Comment by norbusan** [comment]
Your recent changes do not make sense ... we should not pull the installer from ctan, as this will not test the current status.

I need to
- set up a cron job or git postaction that updates this repo whenever files for the installer have changed
- push these changes
- automatically run test on these changes files

Need some time to sort this out.

**Comment by nwhetsell** [comment]
Sorry, I didn’t intend the changes to my fork to end up as part of this pull request.

**Comment by norbusan** [comment]
Can you please update the pull request with changes to that installer zip is not pulled but the files in the repo are used, as they are now. This pull request ATM contains to many different things.

**Comment by nwhetsell** [comment]
Done.

**Pull request merged**
