### PR TITLE
Automatically retry to download packages again later if failed

### PR DESCRIPTION
**Pull request by doraTeX**
I often encounter the following error during network installation of TeX Live.

```
TLPDB::_install_package: downloading did not succeed
Installation failed.
```

This occurs irregularly, that is, at which package the installation aborts varies every time. So, it is probably due to some random network troubles. 

Once the error occurs, the entire installation aborts there, and users should retry from the beginning. So I have tried implementing a workaround in the installation routine based on [@aminophen's suggestion](https://gist.github.com/aminophen/22f5f346b7d4e7d0d452708f2b0aad2c#gistcomment-2867396). His idea is:

* If download of some packages fails, skip them and store them in `@packs_again`.
* After the installation of other packages completed, retry to install the packages stored in `@packs_again`.
* If it fails again, the installation process is to be aborted this time around. However, if the errors are due to random network troubles, the probability of an error occurring twice on the same package should be quite small.

As an experiment, I tried raising network troubles intentionally during network installation. This workaround seems to work well.

### CODE REVIEW

**Comment by norbusan** [comment]
Looks good, can you commit yourself to TeX Live svn, or should I do it for you? Merging here does not really work out for re-committing to svn.

Thanks a lot, good idea!

**Comment by doraTeX** [comment]
@norbusan 
Thank you. I don't have the privilege to commit to TeX Live svn, so may I ask you to commit it to TeX Live svn instead of me?

**Comment by norbusan** [comment]
Thanks, merged into svn!

**Comment by aminophen** [comment]
@doraTeX Thanks a lot ;-)

**Pull request closed without merging**
